version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Ganeshvarikuppala/argo-workflows"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "ansible"